LangString LauncherOptionsHeader ${LANG_TRADCHINESE} "設定類別"
LangString LauncherOptionsHeader2 ${LANG_TRADCHINESE} "請選擇你想使用的類別"
LangString LauncherOptionsIntro ${LANG_TRADCHINESE} "Firefox 的工作階段儲存功能可以替您記下您的瀏覽視窗、分頁、表單記錄，讓您可以在不同的工作階段使用他們，不過在速度較慢的裝置上可能會有效能不佳的問題。您要使用嗎？"
LangString LauncherOptionsOption1 ${LANG_TRADCHINESE} "啟用工作階段儲存功能 (預設)"
LangString LauncherOptionsOption1Description ${LANG_TRADCHINESE} "當你使用的是硬碟或快速的隨身碟則建議選擇此選項"
LangString LauncherOptionsOption2 ${LANG_TRADCHINESE} "關閉工作階段儲存功能"
LangString LauncherOptionsOption2Description ${LANG_TRADCHINESE} "當你使用的是慢速的隨身碟則建議選擇此選項"
LangString LauncherOptionsOutro ${LANG_TRADCHINESE} "未來您依然可以啟用或關閉工作階段儲存功能。你可以在 Mozilla Firefox, Portable Edition 的支援頁面找到相關指示。"