LangString LauncherOptionsHeader ${LANG_ITALIAN} "Tipo d'installazione"
LangString LauncherOptionsHeader2 ${LANG_ITALIAN} "Scegli le opzioni d'installazione"
LangString LauncherOptionsIntro ${LANG_ITALIAN} "La funzionalità Memorizza Sessione di Firefox consente di salvare le tue finestre, le tue schede e il testo nei form da una sessione di navigazione all'altra, ma può causare problemi di prestazioni sui dispositivi più lenti."
LangString LauncherOptionsOption1 ${LANG_ITALIAN} "Abilita Memorizza Sessione (Default)"
LangString LauncherOptionsOption1Description ${LANG_ITALIAN} "Raccomandato per hard drive e flash drive veloci"
LangString LauncherOptionsOption2 ${LANG_ITALIAN} "Disabilita Memorizza Sessione"
LangString LauncherOptionsOption2Description ${LANG_ITALIAN} "Raccomandato per flash drives lenti"
LangString LauncherOptionsOutro ${LANG_ITALIAN} "Puoi abilitare o disabilitare la funzionalità Memorizza Sessione successivamente, seguendo le istruzioni sulla pagina di supporto per Mozilla Firefox, Portable Edition."